# Generated by Django 6.0.3 on 2026-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_piublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
